spring:
  application:
    name: digital-sansad-backend

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  flyway:
    enabled: true
    locations: classpath:db/migration
    validate-migration-naming: true

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

jwt:
  private-key: ${JWT_PRIVATE_KEY}
  public-key: ${JWT_PUBLIC_KEY}
  expiration: 86400000

server:
  port: ${PORT:8080}
  address: 0.0.0.0

logging:
  level:
    root: INFO
    
#below is for docker
# spring:
#   application:
#     name: digital-sansad-backend

#   datasource:
#     url: jdbc:postgresql://${DB_HOST}:5432/${DB_NAME}
#     username: ${DB_USERNAME}
#     password: ${DB_PASSWORD}
#     driver-class-name: org.postgresql.Driver

#   flyway:
#     enabled: true
#     locations: classpath:db/migration
#     validate-migration-naming: true

#   jpa:
#     hibernate:
#       ddl-auto: validate
#     show-sql: true
#     properties:
#       hibernate:
#         format_sql: true
#         default_schema: core

# jwt:
#   private-key: ${JWT_PRIVATE_KEY_PATH:classpath:keys/private_key.pem}
#   public-key: ${JWT_PUBLIC_KEY_PATH:classpath:keys/public_key.pem}
#   expiration: ${JWT_EXPIRATION:86400000}

# server:
#   port: ${SERVER_PORT:8080}

# Below is the hardcoded configuration for local development
# spring:
#   application:
#     name: digital-sansad-backend

#   datasource:
#     url: jdbc:postgresql://localhost:5432/Auth
#     username: postgres
#     password: user123
#     driver-class-name: org.postgresql.Driver

#   flyway:
#     enabled: true
#     locations: classpath:db/migration
#     validate-migration-naming: true

#   jpa:
#     hibernate:
#       ddl-auto: validate
#     show-sql: true
#     properties:
#       hibernate:
#         format_sql: true
#         default_schema: core

# jwt:
#   private-key: classpath:keys/private_key.pem
#   public-key: classpath:keys/public_key.pem
#   expiration: 86400000


# server:
#   port: 8080
